version: "3"
services:
  app:
    image: 'sixfalls/deno:latest'
    user: 'deno'
    restart: unless-stopped
    working_dir: /app
    ports:
      - '80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02
      - ./:/app
    entrypoint: usr/bin/deno
    command: [ "run", "--allow-all", "--unstable", "backend/server.ts" ]
    environment:
      - NPM_IDENTITY
      - NPM_SECRET
      - NPM_URL
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT
      - SUPABASE_AUTH_TOKEN
      - SUPABASE_SERVICE_KEY
      - SUPABASE_URL

networks:
  default:
    name: nginx-proxy-manager_default
