name: Snyk Security Scanner
on: push
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test --sarif-file-output=snyk.sarif
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif